### ISSUE TITLE
Would be better to upgrade 'fs-extra' to latest version (0.22.x => 0.26.x)

### ISSUE THREAD

**Issue by xieguanglei** [GKuChan/co-fs-extra#4]
And support `fs.ensureLink`, `fs.ensureSymlink`, `fs.walk`.

**Comment by dead-horse** [comment]
co-fs-extra@1.2.0

**Comment by xieguanglei** [comment]
Forgot to put `ensureLink` and `ensureSymlink` in `methods.js`? They are still node style methods (with callback) but not chunk.
![2016-02-19 10 03 24](https://cloud.githubusercontent.com/assets/2938447/13164441/33ffce18-d6f0-11e5-804a-db7062ebc041.png)

**Comment by dead-horse** [comment]
sorry, fixed in 1.2.1
